name: Notify Discord

on:
  release:
    types: [published]   # fires when a new release is created

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch release info
        id: release
        uses: actions/github-script@v7
        with:
          script: |
            const release = context.payload.release;
            core.setOutput("tag_name", release.tag_name);
            core.setOutput("body", release.body);

      - name: Send Notification to Discord
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: |
            **New Release: <${{ github.event.release.html_url }}>
