name: Discord Release Notification

on:
  release:
    types: [published, prereleased, edited, released, created]

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        run: |
          echo "Posting release info to Discord..."
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"**New Release:** ${{ github.event.release.name }} (${ { github.event.release.tag_name }} )\n${{ github.event.release.html_url }}\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}