name: Notify Discord
on:
  release:
    types: [published, prereleased, edited]

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@master

        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            🚀 **New Release Published**
            Repository: ${{ github.repository }}
            Release: [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }})
            Author: ${{ github.actor }}
            Name: ${{ github.event.release.name }}
            Description:
            ${{ github.event.release.body }}